services:
# A Service From Doodh Factory 
  - type: web
    name: txt4
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/RaviAreCool/txt4
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: WEBHOOK
        sync: false
      - key: PORT
        sync: false  # Default port value, update if needed
